version: '3.1'
services:
  lar_nginx:
    image: 'nginx:alpine'
    container_name: lar_nginx
    volumes:
      - '.:/var/www/html/basic-laravel'
      - './docker/nginx/conf.d:/etc/nginx/conf.d'
    expose:
      - 80
      - 443
    dns:
      - 8.8.8.8
      - 4.4.4.4
    network_mode: "host"

  lar_php80:
    build: ./docker/php80/php-fpm
    container_name: lar_php80
    working_dir: /var/www/html/basic-laravel
    volumes:
      - '.:/var/www/html/basic-laravel'
      - './docker/php80/supervisor/logs:/var/log/cache'
      - './docker/php80/php-fpm/conf.d/php-ini-overrides.ini:/etc/php/8.0/fpm/conf.d/99-overrides.ini'
    expose:
      - 9000
    dns:
      - 8.8.8.8
      - 4.4.4.4
    network_mode: "host"

  lar_mysql:
    build: ./docker/mysql
    container_name: lar_mysql
    volumes:
      - '.:/var/www/html/basic-laravel'
      - './docker/mysql/data:/var/lib/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=12345@
      - MYSQL_DATABASE=basic-laravel
      - MYSQL_USER=basic-user
      - MYSQL_PASSWORD=basic-password
    expose:
      - 3306
    dns:
      - 8.8.8.8
      - 4.4.4.4
    network_mode: "host"

  lar_redis:
    image: 'redis:alpine'
    container_name: lar_redis
    expose:
      - 6379
    dns:
      - 8.8.8.8
      - 4.4.4.4
    network_mode: "host"
