<?php

namespace Modules\Core\Exceptions;

use App\Exceptions\Handler;
use Symfony\Component\HttpKernel\Exception\HttpException;
use Throwable;

class CoreHandler extends Handler
{
    public function render($request, Throwable $e)
    {
        if ($e instanceof HttpException) {
            $statusCode = (int)$e->getStatusCode();
            $msg = match ($statusCode) {
                401, 403 => 'You are not authorized to view the requested resource.',
                404 => 'The page you requested does not exist.',
                default => 'An error may have occurred.'
            };
            toast($msg, 'error');
            return response()->view('core::error', ['statusCode' => $statusCode, 'msg' => $msg]);
        }

        return parent::render($request, $e); // TODO: Change the autogenerated stub
    }
}
